name: Build ReClass.NET Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: msbuild ReClass.NET.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.7.2

      - name: Debug list output files
        run: |
          Write-Host "Files in Release folder:"
          Get-ChildItem -Path ReClass.NET\bin\Release -Recurse

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReClass.NET
          path: |
            ReClass.NET/bin/Release/*